### PR TITLE
feat+fix: modify configs and refactor cli

### LINKED ISSUE #14: Generated configs fail to marshal
While the generated configuration files are accurate and built from our go structs, once written to YAML it appears we are unable to then unmarshal it back into the structs. This functionality is necessary for being able to edit individual section of config without rewriting the entire file.

I am a bit new to Go so I am not yet aware of the issue and will do more research on this soon, I needed to write it down first so I do not forget.

### PR DESCRIPTION
**Pull request by zenhorace**
This PR does a lot, in short:
- Refactor the CLI to make it more idiomatic Go and make it easier to extend in future development
- The overhaul also fixed  #14 and enabled
- Update command, which takes an input file, allows adding/updating services and outputs a new file with the merger of changes.

I know it's a lot (and you may not like the approach), so take your time, and we can discuss it.

### CODE REVIEW

File: cmd/configure.go [hunk 1]
```diff
@@ -10,14 +10,14 @@ import (
 
 	"github.com/AlecAivazis/survey/v2"
 	"github.com/spf13/cobra"
-	"github.com/techsquidtv/uhs-cli/cmd/common"
-	configCommon "github.com/techsquidtv/uhs-cli/models/common"
+	"github.com/techsquidtv/uhs-cli/cmd/shared"
```
Comment (KyleTryon) [inline cmd/configure.go:13]: love the `shared` change!

File: models/config/config.go [hunk 2]
```diff
@@ -1,19 +1,51 @@
...
+	return nil
+}
 
-	return uhsConfig
+func unmarshalService(key string, data []byte) (manager.Configurer, error) {
+	v, ok := servicemap.Registered[key]
+	if !ok {
+		return nil, fmt.Errorf("unregistered service name: %q", key)
+	}
+	sc := v()
```
Comment (KyleTryon) [inline models/config/config.go:46]: Very nice 👍

**Review by KyleTryon — APPROVED** [review]
Massively appreciate everything you did here @zenhorace. 🙏  This helped me understand a few things about Go and really set us up for a much better foundation moving forward. Huge thanks to you.

**Comment by KyleTryon** [comment]
I'm going to accept everything as it is now, it won't get tagged right away, so we have time to change things before then.
Let me see if i can grab these errors real quick (if you allowed pushing to fork)

**Comment by KyleTryon** [comment]
welp i messed something up there, that was a mistake. instead of pushing to your main i did mine somehow. all cool.. going to fix this retroactively real fast. not the best outcome.
